source:			.
destination:	./_site
plugins:		./_plugins
layouts:		./_layouts
include:		['.htaccess']
exclude:		[]
keep_files:		['.git', '.svn']
gems:			[]
timezone:		nil
encodeing:		nil

#comment before pushing
#url:			http://localhost:4000
#uncomment before pushing
baseurl:		/

title:			Rahul Kadyan
description:	Github project list

owner:
  name:           Rahul Kadyan
  avatar:         bio-photo.png
  email:          mail@rahulkadyan.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        rahulkadyan7
  facebook:       rahulkadyan
  github:         rahulkadyan
  # For Google Authorship https://plus.google.com/authorship
  google_plus:  

disqus_shortname: gsoc2014
future:			true
show_drafts:	nil
limit_posts:	0
highlighter:	pygments

relative_permalinks: true

permalinks:		date
paginate_path:	'/page:num'
paginate:		1

defaults:
    -
      scope:
         path: ""
      values:
         layout: ""
         author: "Rahul Kadyan"

links:
    -  title:	repositories
       url: /
    -  title:	blog
       url: http://blog.rahulkadyan.com
       external: true
    -  title:	portfolio
       url: http://rahulkadyan.com
       external: true